# Wed 8/27 Lecture
### Python and Numpy Basics

Ok this was actually all stuff already known, leaving this doc just for completion's sake.

In [24]:
import numpy as np

In [25]:
u = np.array([1,-4,3])
v = np.array([2,1,5])
print(u.transpose() @ v)
print(v.transpose() @ u)
print(np.outer(u,v))
print(np.linalg.norm(u-v))

13
13
[[  2   1   5]
 [ -8  -4 -20]
 [  6   3  15]]
5.477225575051661
